### ISSUE TITLE
Wrong countries

### ISSUE THREAD

**Issue by mervick** [hakikz/jquery-map-with-time-on-hover#1]
Map have wrong countries:

Ukraine -> Uganda
Azerbaijan -> Austria
Tajikistan -> Chad
Romania -> Qatar
Thailand -> Chad
Slovenia -> Slovakia
Malaysia -> Malawi
Togo -> Chad

![selection_130](https://user-images.githubusercontent.com/2429298/42122605-efd8feda-7c4c-11e8-8d37-47991f01aaf5.png)

**Comment by hakikz** [comment]
Thanks for your contribution. Please check now I have already solved the problem, you have mentioned.
